export const CANCIONES = [
  {
    id: 1,
    cancion: "Cuando Pase el Temblor",
    artista: "Soda Stereo",
    genero: "Rock",
    anio: 1985,
    pistas: [
      "Hay un lugar que conozco...",
      "...donde el viento golpea fuerte.",
      "La tierra tiembla bajo mis pies,",
      "y el cielo se pone de otro color.",
      "Cuando pase el temblor, cuando pase el temblor.",
    ],
    youtube: "https://www.youtube.com/watch?v=_u5f6KqgZPg",
  },
  {
    id: 2,
    cancion: "El Amor Después del Amor",
    artista: "Fito Páez",
    genero: "Rock",
    anio: 1992,
    pistas: [
      "Vengo de un lugar que no existe más...",
      "...donde el frío quemaba igual que el sol.",
      "Tuve miedo y me quedé sin nada,",
      "pero aprendí a vivir sin ilusión.",
      "Necesito del amor después del amor.",
    ],
    youtube: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
  },
  {
    id: 3,
    cancion: "La Balada del Diablo y la Muerte",
    artista: "Divididos",
    genero: "Rock",
    anio: 1993,
    pistas: [
      "Cuentan que en un camino polvoriento...",
      "...se cruzaron dos que no debían.",
      "Uno venía del sur, el otro del norte,",
      "y ninguno quería ceder el paso.",
      "El diablo y la muerte se encontraron.",
    ],
    youtube: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
  },
  {
    id: 4,
    cancion: "De Música Ligera",
    artista: "Soda Stereo",
    genero: "Rock",
    anio: 1990,
    pistas: [
      "Hay algo que no puedo describir...",
      "...que pasa cuando estás cerca.",
      "No es el viento, no es la lluvia,",
      "es algo que me mueve por dentro.",
      "Nada nos libra, nada más queda.",
    ],
    youtube: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
  },
  {
    id: 5,
    cancion: "Persiana Americana",
    artista: "Soda Stereo",
    genero: "Rock",
    anio: 1986,
    pistas: [
      "La veo pasar desde mi ventana...",
      "...cada tarde a la misma hora.",
      "Ella no sabe que la miro,",
      "detrás de la luz que se filtra.",
      "Persiana americana, ay ay ay.",
    ],
    youtube: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
  },
  {
    id: 6,
    cancion: "Mariposa Tecknicolor",
    artista: "Fito Páez",
    genero: "Rock",
    anio: 1992,
    pistas: [
      "Todo se mezcla y no entiendo nada...",
      "...los colores se van y vuelven solos.",
      "Un sueño raro me dejó sin palabras,",
      "y no sé si estoy dormido o despierto.",
      "Mariposa Tecknicolor, vuela vuela.",
    ],
    youtube: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
  },
  {
    id: 7,
    cancion: "Alta Suciedad",
    artista: "Divididos",
    genero: "Rock",
    anio: 1993,
    pistas: [
      "El barrio tiene olor a otra cosa...",
      "...las paredes hablan de otra época.",
      "Nadie limpia lo que está ensuciado,",
      "y el tiempo pasa igual que siempre.",
      "Alta suciedad, alta suciedad.",
    ],
    youtube: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
  },
  {
    id: 8,
    cancion: "Zamba de mi Esperanza",
    artista: "Los Fronterizos",
    genero: "Folklore",
    anio: 1964,
    pistas: [
      "Hay una voz que viene del monte...",
      "...y llega suave hasta mi corazón.",
      "Es el canto de mi tierra querida,",
      "que nunca olvido aunque esté lejos.",
      "Zamba de mi esperanza, florezco en ti.",
    ],
    youtube: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
  },
  {
    id: 9,
    cancion: "Alfonsina y el Mar",
    artista: "Mercedes Sosa",
    genero: "Folklore",
    anio: 1969,
    pistas: [
      "Por la blanda arena que lame el mar...",
      "...su paso pequeño se fue alejando.",
      "Cuando el agua fría mojó su vestido,",
      "nadie la llamó para que volviera.",
      "Alfonsina y el mar, juntas para siempre.",
    ],
    youtube: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
  },
  {
    id: 10,
    cancion: "Todo Pasa",
    artista: "Tan Biónica",
    genero: "Pop Rock",
    anio: 2010,
    pistas: [
      "A veces siento que no hay salida...",
      "...que el mundo se cierra alrededor.",
      "Pero algo me dice que es mentira,",
      "que mañana va a ser diferente.",
      "Todo pasa, todo pasa, ya verás.",
    ],
    youtube: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
  },
  {
    id: 11,
    cancion: "Corazón Delator",
    artista: "Tan Biónica",
    genero: "Pop Rock",
    anio: 2011,
    pistas: [
      "Algo me late más rápido que antes...",
      "...y no sé si es miedo o alegría.",
      "Cada vez que aparecés de repente,",
      "no puedo disimular lo que siento.",
      "Mi corazón delator me traiciona.",
    ],
    youtube: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
  },
  {
    id: 12,
    cancion: "La Rubia Tarada",
    artista: "Los Fabulosos Cadillacs",
    genero: "Ska Rock",
    anio: 1989,
    pistas: [
      "La vi pasar y me quedé mirando...",
      "...no podía creer lo que veían mis ojos.",
      "Caminaba diferente a todas,",
      "con ese estilo que nadie explica.",
      "La rubia tarada pasó y me volvió loco.",
    ],
    youtube: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
  },
  {
    id: 13,
    cancion: "Matador",
    artista: "Los Fabulosos Cadillacs",
    genero: "Ska Rock",
    anio: 1993,
    pistas: [
      "Hay alguien que camina entre la gente...",
      "...y nadie sabe bien de dónde viene.",
      "Su mirada fría no dice nada,",
      "pero todos saben que hay que tener cuidado.",
      "Matador, matador, todos corren.",
    ],
    youtube: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
  },
  {
    id: 14,
    cancion: "Loco Tu Manera",
    artista: "Árbol",
    genero: "Rock",
    anio: 2004,
    pistas: [
      "No entiendo cómo hacés para sonreír...",
      "...cuando todo parece estar al revés.",
      "Tenés algo especial que no se aprende,",
      "y que a mí me cuesta tanto encontrar.",
      "Loca tu manera de ver la vida.",
    ],
    youtube: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
  },
  {
    id: 15,
    cancion: "Me Voy Enamorando",
    artista: "Chayanne",
    genero: "Pop",
    anio: 2007,
    pistas: [
      "Algo está pasando dentro de mí...",
      "...que no puedo controlar ni entender.",
      "Cada vez que te veo llegar,",
      "mi mundo cambia sin que yo lo decida.",
      "Me voy enamorando poco a poco de ti.",
    ],
    youtube: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
  },
  {
    id: 16,
    cancion: "No Me Arrepiento de Este Amor",
    artista: "Gilda",
    genero: "Cumbia",
    anio: 1994,
    pistas: [
      "La gente habla y no para de hablar...",
      "...dicen que estoy equivocada.",
      "Pero yo sé lo que siento por vos,",
      "y nadie me va a hacer cambiar de idea.",
      "No me arrepiento de este amor.",
    ],
    youtube: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
  },
  {
    id: 17,
    cancion: "Fue Amor",
    artista: "Gilda",
    genero: "Cumbia",
    anio: 1996,
    pistas: [
      "Todavía recuerdo la primera vez...",
      "...que me miraste diferente a todos.",
      "Algo pasó entre nosotros esa noche,",
      "que ninguno de los dos pudo evitar.",
      "Fue amor, fue amor lo que sentimos.",
    ],
    youtube: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
  },
  {
    id: 18,
    cancion: "Soy Tuyo",
    artista: "Los Palmeras",
    genero: "Cumbia",
    anio: 1995,
    pistas: [
      "Desde que llegaste a mi vida...",
      "...nada volvió a ser lo mismo.",
      "Me cambiaste sin que yo me diera cuenta,",
      "y ahora no me imagino sin vos.",
      "Soy tuyo, completamente tuyo.",
    ],
    youtube: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
  },
  {
    id: 19,
    cancion: "Color Esperanza",
    artista: "Diego Torres",
    genero: "Pop",
    anio: 2001,
    pistas: [
      "Sé que hay en tus ojos con solo mirar...",
      "...que estás cansado de andar y de andar.",
      "Y caminar sin rumbo fijo es triste,",
      "pero algo dentro tuyo dice que no.",
      "Vale la pena el color esperanza.",
    ],
    youtube: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
  },
  {
    id: 20,
    cancion: "Inevitable",
    artista: "Shakira",
    genero: "Pop",
    anio: 2001,
    pistas: [
      "Sabía que ibas a volver...",
      "...aunque dijiste que no lo harías.",
      "Algunas cosas no se pueden evitar,",
      "como el sol que sale cada mañana.",
      "Inevitable, inevitable, volver a verte.",
    ],
    youtube: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
  },
]

export const CANCION_DEL_DIA = () => {
  const inicio = new Date('2025-01-01')
  const hoy = new Date()
  const diff = Math.floor((hoy - inicio) / (1000 * 60 * 60 * 24))
  return CANCIONES[diff % CANCIONES.length]
}